
when:
  - event:  [push, manual]
    branch: trunk

matrix:
  release:
    - 29-alpine
    - 28-alpine
    - 27-alpine

steps:
  - name: erlang_job
    image: erlang:${release}

    commands:
    - uname -a
    - rebar3 compile
    - rebar3 dialyzer
    - rebar3 eunit
